---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop:latest
    restart: "no"
    ports:
      - "8888:9000"
    environment:
      KAFKA_BROKERCONNECT: "broker:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - broker

  generator:
    container_name: generator
    image: ruivieira/anomaly-generator
    build:      
      context: ./anomaly-generator
    depends_on:
      - broker
    ports:
      - "5000:5000"
    environment:
      - PERIOD=24
      - AMPLITUDE=100
      - ERROR=20
      - MEAN=200
      - PYTHONUNBUFFERED=1


  anomaly-detector:
    container_name: anomaly-detector
    image: ruivieira/anomaly-detector
    ports:
      - "9000:9000"
    build:      
      context: ./anomaly-detection
    environment:
      - PYTHONUNBUFFERED=1
  
  drift-detector:
    container_name: drift-detector
    image: ruivieira/drift-detector
    ports:
      - "8897:9000"
    build:      
      context: ./drift-detector
    environment:
      - PYTHONUNBUFFERED=1

  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise:8.2.0
    ports:
      - "3000:3000"
    user: '104'

  test-bridge:
    container_name: test-bridge
    image: ruivieira/test-bridge
    build:      
      context: ./test-bridge
    depends_on:
      - broker
      - generator
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8502:8501"

